version: "3.3"

services:
  front-end:
    build:
      context: ./timesheets_frontend
    volumes:
      - ./timesheets_frontend:/app
      - /timesheets_frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

networks:
  webnet:
